previewsEnabled: true
services:
  - type: web
    name: newsletter web app
    plan: starter
    previewPlan: starter
    env: static
    buildCommand: yarn build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
