previewsEnabled: true
services:
  - type: web
    name: prod newsletter web app
    plan: starter
    env: static
    repo: https://github.com/rgarbi/gospel-message-web-app
    branch: main
    buildCommand: yarn build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    domains:
      - subscribe.gospelmessage.net
    
  - type: web
    name: staging newsletter web app
    plan: starter
    env: static
    repo: https://github.com/rgarbi/gospel-message-web-app
    branch: staging
    buildCommand: yarn build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    domains:
      - staging-subscribe.gospelmessage.net